-- Stage 3: Evidence engine adjudication columns on adjustment_proposals
--
-- Adds the four columns the discovery runner's Phase 4.5 evidence
-- adjudication writes for each persisted proposal. The frontend can
-- start rendering tier badges as soon as it adopts these fields; the
-- backend writes them on every new discovery run.
--
-- All columns are nullable (or default to []) so existing rows are
-- unaffected and the migration is fully reversible. Frontend code
-- that doesn't read these columns continues to work unchanged.

ALTER TABLE public.adjustment_proposals
  ADD COLUMN IF NOT EXISTS support_tier integer,
  ADD COLUMN IF NOT EXISTS support_tier_label text,
  ADD COLUMN IF NOT EXISTS evidence_report jsonb,
  ADD COLUMN IF NOT EXISTS missing_evidence jsonb NOT NULL DEFAULT '[]'::jsonb;

COMMENT ON COLUMN public.adjustment_proposals.support_tier IS
  'Evidence engine SupportTier 0-4 assigned in discovery Phase 4.5. NULL for proposals created before Stage 3 or where adjudication failed.';

COMMENT ON COLUMN public.adjustment_proposals.support_tier_label IS
  'Human-readable label for support_tier (e.g. "Independently corroborated", "Management asserted").';

COMMENT ON COLUMN public.adjustment_proposals.evidence_report IS
  'Full serialized EvidenceReport including sources_checked, items, and assessment_narrative. Mirrors the verification report structure.';

COMMENT ON COLUMN public.adjustment_proposals.missing_evidence IS
  'List of suggestions for documents/data that would strengthen this claim, generated by app.evidence.protocols.suggest_missing_evidence.';

-- Index on support_tier for the frontend's likely "show me tier-4 only"
-- and "filter out tier 0/1" queries on the proposal list.
CREATE INDEX IF NOT EXISTS idx_adjustment_proposals_support_tier
  ON public.adjustment_proposals (support_tier);
