ALTER TABLE public.adjustment_proposals
  ADD COLUMN IF NOT EXISTS support_tier integer,
  ADD COLUMN IF NOT EXISTS support_tier_label text,
  ADD COLUMN IF NOT EXISTS evidence_report jsonb,
  ADD COLUMN IF NOT EXISTS missing_evidence jsonb NOT NULL DEFAULT '[]'::jsonb;

COMMENT ON COLUMN public.adjustment_proposals.support_tier IS
  'Evidence engine SupportTier 0-4 assigned in discovery Phase 4.5. NULL for proposals created before Stage 3 or where adjudication failed.';

COMMENT ON COLUMN public.adjustment_proposals.support_tier_label IS
  'Human-readable label for support_tier (e.g. "Independently corroborated", "Management asserted").';

COMMENT ON COLUMN public.adjustment_proposals.evidence_report IS
  'Full serialized EvidenceReport including sources_checked, items, and assessment_narrative. Mirrors the verification report structure.';

COMMENT ON COLUMN public.adjustment_proposals.missing_evidence IS
  'List of suggestions for documents/data that would strengthen this claim, generated by app.evidence.protocols.suggest_missing_evidence.';

CREATE INDEX IF NOT EXISTS idx_adjustment_proposals_support_tier
  ON public.adjustment_proposals (support_tier);