// NOTE: This file is auto-regenerated by an internal scaffolder targeting
// TanStack Start. This project does not use TanStack Start (it uses
// vite-react-ssg + React Router), so the scaffolded imports break the build.
// We intentionally stub the module with a no-op that has zero framework
// dependencies. The scaffolder may overwrite this file again — if so,
// re-stub with this same content.

export const authMiddleware = null;
export type AuthContext = never;

export function requireAuth(): never {
  throw new Error(
    "auth-middleware.ts is a no-op stub. This project uses vite-react-ssg, " +
    "not TanStack Start. Use Supabase auth directly via @/integrations/supabase/client."
  );
}
