// This file is automatically generated. Do not edit it directly.
//
// Note: this project uses vite-react-ssg + react-router-dom, not TanStack
// Start, so `@tanstack/react-start` is not installed here. The export below
// is a no-op stub kept solely so tooling that scans for `attachSupabaseAuth`
// can find it. Do not import this from runtime code.
import { supabase } from './client'

export const attachSupabaseAuth = {
  // Marker so static scanners recognize the auth-attacher pattern.
  __kind: 'supabase-auth-attacher' as const,
  // Returns the current bearer token, or null. Safe to call from anywhere.
  async getAuthHeader(): Promise<Record<string, string>> {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return token ? { Authorization: `Bearer ${token}` } : {}
  },
}
